In [1]:
import numpy as np

In [2]:
a = np.random.randint(1, 10, 9).reshape(3,3)
print(a)

[[2 7 7]
 [4 7 6]
 [7 3 9]]


In [5]:
b = np.apply_along_axis(sorted, 0, a)
print(b)

[[2 3 6]
 [4 7 7]
 [7 7 9]]
