In [2]:
import numpy as np

<a id="section- section-nine "></a>
# Section 9 - Comparisons, Masks, and Boolean Logic

In [3]:
x = np.array([1,2,3,4,5])
x < 3

array([ True,  True, False, False, False])

In [4]:
x > 3

array([False, False, False,  True,  True])

In [5]:
x == 3

array([False, False,  True, False, False])

In [6]:
(x*2) == (x**2)

array([False,  True, False, False, False])

In [7]:
rng = np.random.RandomState(0)
x = rng.randint(12, size=(3,4))
x

array([[ 5,  0,  3, 11],
       [ 3,  7,  9,  3],
       [ 5,  2,  4,  7]], dtype=int32)

In [8]:
x < 6

array([[ True,  True,  True, False],
       [ True, False, False,  True],
       [ True,  True,  True, False]])

In [9]:
print(x)

[[ 5  0  3 11]
 [ 3  7  9  3]
 [ 5  2  4  7]]


In [10]:
np.count_nonzero(x<6)

np.int64(8)

In [11]:
np.sum(x < 6)

np.int64(8)

In [12]:
np.sum(x < 6, axis=1)

array([3, 2, 3])

In [13]:
np.sum((x < 6), axis=0)

array([3, 2, 2, 1])

In [14]:
np.any(x < 0)

np.False_

In [15]:
np.all(x == 6)

np.False_

In [16]:
np.all(x < 8, axis=1)

array([False, False,  True])

In [17]:
x[x<5]

array([0, 3, 3, 3, 2, 4], dtype=int32)