In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
a.reshape(-1)

array([1, 2, 3, 4])

In [4]:
b = np.array([[1,2], [3,4]])
b

array([[1, 2],
       [3, 4]])

In [5]:
b.ravel()

array([1, 2, 3, 4])