In [2]:
import numpy as np

In [3]:
name = ['Alice', 'Bob', 'Cathy', 'Doug']
age = [25,45,37,19]
weight = [55.0,85.5,68.0,61.5]

data = np.zeros(4, dtype={'names':('name', 'age', 'weight'), 'formats':('U10', 'i4', 'f8')})
print(data.dtype)

[('name', '<U10'), ('age', '<i4'), ('weight', '<f8')]


In [4]:
data['name'] = name
data['age'] = age
data['weight'] = weight
print(data)

[('Alice', 25, 55. ) ('Bob', 45, 85.5) ('Cathy', 37, 68. )
 ('Doug', 19, 61.5)]


In [6]:
data['name']

array(['Alice', 'Bob', 'Cathy', 'Doug'], dtype='<U10')

In [8]:
print(data[0])

('Alice', 25, 55.0)


In [9]:
print(data[-1]['name'])

Doug


In [10]:
data[data['age'] < 30]['name']

array(['Alice', 'Doug'], dtype='<U10')

In [12]:
np.dtype({'names': ('name', 'age', 'weight'), 'formats':((np.str_, 10), int, np.float32)})

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f4')])

In [13]:
np.dtype({'names': ('name', 'age', 'weight'), 'formats': ('U10', 'i4', 'f8')})

dtype([('name', '<U10'), ('age', '<i4'), ('weight', '<f8')])

In [15]:
np.dtype([('name', 'U10'), ('age', 'i8'), ('weight', 'f8')])

dtype([('name', '<U10'), ('age', '<i8'), ('weight', '<f8')])

In [16]:
np.dtype('S10,i4,f8')

dtype([('f0', 'S10'), ('f1', '<i4'), ('f2', '<f8')])

In [17]:
tp = np.dtype([('id', 'i8'), ('mat', 'f8', (3,3))])
X = np.zeros(1, dtype=tp)
print(X[0])
print(X['mat'][0])

(0, [[0.0, 0.0, 0.0], [0.0, 0.0, 0.0], [0.0, 0.0, 0.0]])
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [18]:
data_rec = data.view(np.recarray)
data_rec.age

array([25, 45, 37, 19], dtype=int32)

In [19]:
%timeit data['age']
%timeit data_rec['age']
%timeit data_rec.age 

169 ns ± 0.897 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)
2.53 μs ± 19.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
5.3 μs ± 97.2 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
