In [1]:
import numpy as np

In [3]:
a = np.random.randint(0, 10, (3,3))
print('Before a: \n', a)

Before a: 
 [[9 9 0]
 [1 1 7]
 [6 3 4]]


In [4]:
a = np.random.randint(0, 10, (3,3))

print('Beofre a: \n', a)
print('After a: \n')
b = a[a[:,2].argsort()]
print(b)

Beofre a: 
 [[8 1 3]
 [0 3 2]
 [8 5 6]]
After a: 

[[0 3 2]
 [8 1 3]
 [8 5 6]]
