In [1]:
import numpy as np

In [2]:
x = np.arange(9).reshape(1,3,3)
x

array([[[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]]])

In [5]:
y =np.array(np.squeeze(x))
print(y)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [8]:
print(x.shape, y.shape)

(1, 3, 3) (3, 3)
