In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3], [4,8,16]])
a 

array([[ 1,  2,  3],
       [ 4,  8, 16]])

In [3]:
b = np.array([5,6,11]).reshape(-1,1)
b

array([[ 5],
       [ 6],
       [11]])

In [4]:
np.dot(a,b)

array([[ 50],
       [244]])