In [1]:
import pandas as pd
import numpy as np

In [6]:
df = pd.DataFrame({
    'a1': [1,2,3],
    'a2': [4,5,6],
    'a3': [7,8,9]
})

print(df)

x = df.to_numpy()
print('\n DataFrame to numpy array: ') 
print(x)

y = df.index.to_numpy()
print('\n DataFrame indices to Numpy') 
print(y)

z = df['a1'].to_numpy()
print('\n DataFrame series to Numpy')
print(z)

   a1  a2  a3
0   1   4   7
1   2   5   8
2   3   6   9

 DataFrame to numpy array: 
[[1 4 7]
 [2 5 8]
 [3 6 9]]

 DataFrame indices to Numpy
[0 1 2]

 DataFrame series to Numpy
[1 2 3]
