In [1]:
import numpy as np

In [2]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x,y, out=y)
print(y)

[0.00000000e+000 9.51738382e-312 1.90347676e-311 2.85521514e-311
 0.00000000e+000]


In [3]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [4]:
x = np.arange(6)
print(np.add.reduce(x))

15


In [5]:
np.multiply.reduce(x)

np.int64(0)

In [6]:
np.add.accumulate(x)

array([ 0,  1,  3,  6, 10, 15])

In [7]:
x = np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])