In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [5]:
b = np.array([
    [4],
    [5],
    [6],
    [7]
])

b

array([[4],
       [5],
       [6],
       [7]])

In [6]:
np.dot(a,b)

array([60])

In [8]:
a.dot(b)

array([60])