In [1]:
import numpy as np

In [3]:
a = np.array([[1,2,3], [2,3,6], [6,7,2]])
print('Original: \n', a)

Original: 
 [[1 2 3]
 [2 3 6]
 [6 7 2]]


In [5]:
print('triu() without any parameter: \n', np.triu(a))

triu() without any parameter: 
 [[1 2 3]
 [0 3 6]
 [0 0 2]]


In [7]:
print('triu() with any parameter: \n', np.triu(a, 1))

triu() with any parameter: 
 [[0 2 3]
 [0 0 6]
 [0 0 0]]


In [8]:
print('triu() with any parameter: \n', np.triu(a, -1))

triu() with any parameter: 
 [[1 2 3]
 [2 3 6]
 [0 7 2]]
