In [7]:
import numpy as np

In [8]:
a = np.eye(2)
a

array([[1., 0.],
       [0., 1.]])

In [9]:
b = np.array([[1,2], [3,4]])
print(b)

[[1 2]
 [3 4]]


In [10]:
np.matmul(a,b)

array([[1., 2.],
       [3., 4.]])

In [11]:
np.multiply(a,b)

array([[1., 0.],
       [0., 4.]])