In [1]:
import numpy as np

In [2]:
a = np.random.randint(0, 10, 20).reshape(4,5)

print(a)

[[4 1 4 0 9]
 [2 2 1 2 4]
 [9 5 3 3 0]
 [0 6 9 2 0]]


In [4]:
b = a[:,4] > 2

print(b)

[ True  True False False]


In [5]:
c = a[2,:] > 2
print(c)

[ True  True  True  True False]
