In [3]:
import numpy as np

In [4]:
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
        return output
    
values = np.random.randint(1, 10, size=5)
compute_reciprocals(values)

array([1.66666667e-001, 1.04416860e-311, 1.04416860e-311, 1.04416860e-311,
       1.04416860e-311])

In [5]:
big_array = np.random.randint(1, 100, size=1000000)
%timeit compute_reciprocals(big_array)

37.7 μs ± 414 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [6]:
print(compute_reciprocals(values))
print(1.0 / values)

[1.66666667e-001 1.04416860e-311 1.04416860e-311 1.04416860e-311
 1.04416860e-311]
[0.16666667 1.         0.25       0.25       0.125     ]


In [7]:
%timeit (1.0 / big_array)

2.7 ms ± 92.8 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [9]:
np.arange(1,6)

array([1, 2, 3, 4, 5])

In [10]:
x = np.arange(9).reshape(3,3)
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

In [11]:
x = np.arange(4)
print("x  =", x)
print("x+5 =",x+5)
print("x+2 =",x+2)
print("x+8 =",x+8)

x  = [0 1 2 3]
x+5 = [5 6 7 8]
x+2 = [2 3 4 5]
x+8 = [ 8  9 10 11]


In [12]:
f = lambda n, m: n + m ** 2
s = np.fromfunction(f, (6,6), dtype=int)
print(s)

[[ 0  1  4  9 16 25]
 [ 1  2  5 10 17 26]
 [ 2  3  6 11 18 27]
 [ 3  4  7 12 19 28]
 [ 4  5  8 13 20 29]
 [ 5  6  9 14 21 30]]


In [13]:
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [14]:
print("-x =", -x)
print("x ** 2 =", x ** 2)
print("x % 2 =", x % 2)

-x = [ 0 -1 -2 -3]
x ** 2 = [0 1 4 9]
x % 2 = [0 1 0 1]


In [15]:
-(0.5 * x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [16]:
x = np.array([-2,-3,5.6,-8.6,45.2])
print(abs(x))

print(np.absolute(x))

y=np.array([3,4j,4+8j,2+99j])
print(np.absolute(y))

[ 2.   3.   5.6  8.6 45.2]
[ 2.   3.   5.6  8.6 45.2]
[ 3.          4.          8.94427191 99.02019996]


In [17]:
theta = np.linspace(0, np.pi, 3)

print("theta =", theta)
print("sin(theta) =", np.sin(theta))
print("cos(theta) =", np.cos(theta))
print("tan(theta) =", np.tan(theta))

theta = [0.         1.57079633 3.14159265]
sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [18]:
x = [-1, 0, 1]
print("x =", x)
print("arcsin(x) =", np.arcsin(x))
print("arcos(x) =", np.arccos(x))
print("arctan(x) =", np.arctan(x))

x = [-1, 0, 1]
arcsin(x) = [-1.57079633  0.          1.57079633]
arcos(x) = [3.14159265 1.57079633 0.        ]
arctan(x) = [-0.78539816  0.          0.78539816]


In [19]:
x = [1,2,3]
print("x =", x)
print("e^x =", np.exp(x))
print("2^x =", np.exp2(x))
print("3^x =", np.power(3, x))

x = [1, 2, 3]
e^x = [ 2.71828183  7.3890561  20.08553692]
2^x = [2. 4. 8.]
3^x = [ 3  9 27]


In [20]:
x = [1,2,4,10]

print("x =", x)
print("in(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
in(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [21]:
x = [0, 0.001, 0.01, 0.1]
print("exp(x) - 1 =", np.expm1(x))
print("log(1+x) =", np.log1p(x))

exp(x) - 1 = [0.         0.0010005  0.01005017 0.10517092]
log(1+x) = [0.         0.0009995  0.00995033 0.09531018]
