In [1]:
import numpy as np

In [2]:
X = np.arange(12).reshape(6,2)
print(X)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]]


# Options: 
- 'C' - # C-like index ordering
- 'F' - # Fortran-like index ordering
- 'A' - # Mixed Fortran or C (check docucmnetation for more)

In [4]:
Y = X.reshape(3,2,2, order='F')
print(Y)

[[[ 0  1]
  [ 6  7]]

 [[ 2  3]
  [ 8  9]]

 [[ 4  5]
  [10 11]]]


In [5]:
D = X.reshape(3,2,2,order='C')
print(D)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]


In [6]:
S = X.reshape(3,2,2,order='A')
print(S)

[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]]
