In [1]:
import numpy as np

In [2]:
x = np.array([2,1,3,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [3]:
x.sort()
print(x)

[1 2 3 4 5]


In [4]:
x = np.array([2,1,4,3,5])
i = np.argsort(x)
print(i)

[1 0 3 2 4]


In [5]:
x[i]

array([1, 2, 3, 4, 5])

In [6]:
rand = np.random.RandomState(42)
X = rand.randint(0, 10, (4,6))
print(X)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [7]:
np.sort(X, axis=1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]], dtype=int32)

In [8]:
np.sort(X, axis=0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]], dtype=int32)

In [9]:
x = np.array([7,2,3,1,6,5,4])
np.partition(x,2)

array([1, 2, 3, 7, 6, 5, 4])

In [10]:
np.partition(X, 2,axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]], dtype=int32)

In [11]:
X = rand.rand(19, 2)

plt.scatter(X[:, 0], X[:, 1], s=100)

NameError: name 'plt' is not defined

In [ ]:
dist_sq = np.sum((X[:, np.newaxis,:] - X[np.newaxis,:,:]) ** 2, axis=-1)

In [ ]:
differences = X[:, np.newaxis, :] - X[np.newaxis, :, :]
differences.shape

(19, 19, 2)