In [1]:
import numpy as np

In [2]:
a = np.arange(6).reshape(2, -1)
print(a)

[[0 1 2]
 [3 4 5]]


In [3]:
b = a.transpose()
print(b)

[[0 3]
 [1 4]
 [2 5]]


In [4]:
c = np.transpose(a)
print(c)

[[0 3]
 [1 4]
 [2 5]]
