In [1]:
import numpy as np

In [2]:
def get_avg(a):
    return (a[0] + a[-1]) / 2

a = np.random.randint(1, 10, 9).reshape(3,3)

print(a)

[[8 5 3]
 [4 6 4]
 [3 1 5]]


In [3]:
b = np.apply_along_axis(get_avg, 0, a)
print(b)

[5.5 3.  4. ]


In [4]:
c = np.apply_along_axis(sorted, 0, a)
print(c)

[[3 1 3]
 [4 5 4]
 [8 6 5]]
