In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
b = np.array([4,4,3])

c = np.multiply.outer(a, b)

print(c)

[[ 4  4  3]
 [ 8  8  6]
 [12 12  9]]


In [3]:
d = c.ravel()
print(d)

[ 4  4  3  8  8  6 12 12  9]
