In [1]:
import numpy as np

In [2]:
a = np.array([[1,2], [3,4]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
a.T

array([[1, 3],
       [2, 4]])

In [5]:
a.transpose()

array([[1, 3],
       [2, 4]])