In [ ]:
import numpy as np

In [ ]:
L = np.random.random(110)
sum(L)

np.float64(55.955149666743715)

In [ ]:
np.sum(L)

np.float64(55.95514966674374)

In [ ]:
big_array = np.random.rand(1000000)
%timeit sum(big_array)
%timeit np.sum(big_array)

106 ms ± 1.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
968 μs ± 72.3 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [ ]:
min(big_array)

np.float64(7.071203171893359e-07)

In [ ]:
max(big_array)

np.float64(0.9999997207656334)

In [ ]:
M =np.random.random((3,4))
print(M)

[[0.37497044 0.22944653 0.07452786 0.41843762]
 [0.99939192 0.66974416 0.54717434 0.82711104]
 [0.23097044 0.16283152 0.27950484 0.58540569]]


In [ ]:
M.sum()

np.float64(5.399516404204364)

In [ ]:
M.min(axis=0)

array([0.23097044, 0.16283152, 0.07452786, 0.41843762])

In [ ]:
M.max(axis=0)

array([0.99939192, 0.66974416, 0.54717434, 0.82711104])

In [ ]:
M.min(axis=1)

array([0.07452786, 0.54717434, 0.16283152])

In [ ]:
M.max(axis=1)

array([0.41843762, 0.99939192, 0.58540569])