In [1]:
import numpy as np

In [2]:
x = np.array([1,2,3,4,5,6], dtype=np.float32)
print(x)

[1. 2. 3. 4. 5. 6.]


In [3]:
x.astype(np.int16)

array([1, 2, 3, 4, 5, 6], dtype=int16)

In [4]:
x.astype(np.bool)

array([ True,  True,  True,  True,  True,  True])