In [1]:
import numpy as np

In [2]:
a = np.array([[10,20,30], [100,200,300]])
print(a)

[[ 10  20  30]
 [100 200 300]]


In [4]:
permutation = [1,0]
b = a[permutation]
print(b)

[[100 200 300]
 [ 10  20  30]]
