In [2]:
import numpy as np
import re

In [3]:
a_list = '''
[[25 3 2]
 [1 21 0]
 [1 0 0]]
'''
print(a_list)



[[25 3 2]
 [1 21 0]
 [1 0 0]]



In [5]:
rows = []

for line in filter(len, map(str.strip, a_list.split("\n"))):
    rows.append([int(v) for v in re.findall(r"\b[0-9]+\b", line)])

print(rows)

[[25, 3, 2], [1, 21, 0], [1, 0, 0]]


In [6]:
np_rows = np.array(rows)
print(np_rows)

[[25  3  2]
 [ 1 21  0]
 [ 1  0  0]]


In [7]:
np_rows += 2
print(np_rows)

[[27  5  4]
 [ 3 23  2]
 [ 3  2  2]]


In [8]:
print(type(np_rows))

<class 'numpy.ndarray'>
