In [2]:
import numpy as np

In [3]:
a = np.array([range(i, i +3) for i in [2,3,4]])
print(a)

[[2 3 4]
 [3 4 5]
 [4 5 6]]


In [4]:
bb= np.zeros(100, dtype=int)
print(bb)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [5]:
tt = np.ones((3, 5), dtype=float)
print(tt)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [6]:
qw = np.full((3, 5), 3.14)
print(qw)

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]


In [7]:
er = np.arange(0, 20, 2)
print(er)

[ 0  2  4  6  8 10 12 14 16 18]


In [8]:
op = np.linspace(0, 1, 10)
print(op)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [9]:
np.random.random((3,3))

array([[0.72258714, 0.34848153, 0.14057802],
       [0.94974118, 0.60742391, 0.26973183],
       [0.64962035, 0.16624344, 0.29550639]])

In [10]:
np.random.normal(0, 1, (3,3))

array([[-0.7950143 ,  0.4154498 , -0.28791356],
       [-0.34996064, -0.66794016,  0.34838863],
       [-0.27765043,  1.05061556, -0.05685398]])

In [11]:
np.random.randint(0, 10, (3,3))

array([[8, 2, 4],
       [3, 4, 2],
       [4, 5, 1]], dtype=int32)

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.empty(3)

array([1., 1., 1.])

In [14]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))

print(x1)
print("x1: ndim=", x1.ndim)
print("x1: shape=",x1.shape)
print("x1: size=",x1.size)
print("x1: dtype=", x1.dtype)
print("x1: itemsize=", x1.itemsize, "bytes")
print("x1: nbytes=", x1.nbytes, "bytes")
print('\n')
print(x2)
print("x2: ndim=", x2.ndim)
print("x2: shape=",x2.shape)
print("x2: size=",x2.size)
print("x2: dtype=", x2.dtype)
print("x2: itemsize=", x2.itemsize, "bytes")
print("x2: nbytes=", x2.nbytes, "bytes")
print('\n')
print(x3)
print("x3: ndim=", x3.ndim)
print("x3: shape=",x3.shape)
print("x3: size=",x3.size)
print("x3: dtype=", x3.dtype)
print("x3: itemsize=", x3.itemsize, "bytes")
print("x3: nbytes=", x3.nbytes, "bytes")

[5 0 3 3 7 9]
x1: ndim= 1
x1: shape= (6,)
x1: size= 6
x1: dtype= int32
x1: itemsize= 4 bytes
x1: nbytes= 24 bytes


[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
x2: ndim= 2
x2: shape= (3, 4)
x2: size= 12
x2: dtype= int32
x2: itemsize= 4 bytes
x2: nbytes= 48 bytes


[[[8 1 5 9 8]
  [9 4 3 0 3]
  [5 0 2 3 8]
  [1 3 3 3 7]]

 [[0 1 9 9 0]
  [4 7 3 2 7]
  [2 0 0 4 5]
  [5 6 8 4 1]]

 [[4 9 8 1 1]
  [7 9 9 3 6]
  [7 2 0 3 5]
  [9 4 4 6 4]]]
x3: ndim= 3
x3: shape= (3, 4, 5)
x3: size= 60
x3: dtype= int32
x3: itemsize= 4 bytes
x3: nbytes= 240 bytes


In [15]:
x1
x2[0]
x2[2]

array([1, 6, 7, 7], dtype=int32)

In [16]:
x2[0,0]

np.int32(3)

In [17]:
x2[2,0]

np.int32(1)

In [18]:
x2[0,-1]

np.int32(4)

In [19]:
x2[:2, :3]

array([[3, 5, 2],
       [7, 6, 8]], dtype=int32)

In [20]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [21]:
t = x2[:2, :2]
print(t)

[[3 5]
 [7 6]]


In [22]:
t[0,0] = 99
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]
