In [2]:
import numpy as np

In [3]:
np.random.seed(0)
x1 = np.random.randint(10, size=6)
x2 = np.random.randint(10, size=(3, 4))
x3 = np.random.randint(10, size=(3, 4, 5))


In [4]:
print(x2)

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]


In [5]:
x2_subset = x2[:2, :2].copy()
print(x2_subset)

[[3 5]
 [7 6]]


In [6]:
grid_3D = np.arange(1, 10).reshape(3,3)
print(grid_3D)

grid_10D = np.arange(1, 101).reshape(10, 10)
print(grid_10D)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]


In [7]:
n = np.array([1,2,7])
print(n)

[1 2 7]


In [8]:
n.reshape(1,3)

array([[1, 2, 7]])

In [9]:
n[np.newaxis, :]

array([[1, 2, 7]])

In [10]:
n.reshape(3,1)

array([[1],
       [2],
       [7]])

In [11]:
n[:, np.newaxis]

array([[1],
       [2],
       [7]])

In [12]:
x = np.array([2,3,4,7])
y = np.array([6,7,8,9])
t = np.concatenate([x,y])
print(t)

z = np.array([88,33,45])
p = np.array([67,71,82])
t1 = np.concatenate([x,y,z,p])
print(t1)

[2 3 4 7 6 7 8 9]
[ 2  3  4  7  6  7  8  9 88 33 45 67 71 82]


In [13]:
grid = np.array([[1,2,3], [4,5,6]])
bb = np.concatenate([grid, grid])
print(bb)

[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]


In [14]:
bb1 = np.concatenate([grid, grid], axis=1)
print(bb1)

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [15]:
x10 = np.array([1,2,3])
x11 = np.array([[9,8,7], [6,5,4]])

output = np.vstack([x10, x11])
print(output)

[[1 2 3]
 [9 8 7]
 [6 5 4]]


In [16]:
y = np.array([[99], [99]])

np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [17]:
x = [1,2,3,99,99,3,2,1]
x1, x2, x3 = np.split(x, [3,5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [18]:
grid = np.arange(16).reshape(4,4)
print(grid)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [19]:
upper, lower = np.vsplit(grid, [2])

In [20]:
print(upper)

[[0 1 2 3]
 [4 5 6 7]]


In [21]:
print(lower)

[[ 8  9 10 11]
 [12 13 14 15]]


In [22]:
left, right = np.hsplit(grid, [2])

In [23]:
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
