In [1]:
import numpy as np

In [2]:
x = np.arange(1,7).reshape(2,3)
print(x)

[[1 2 3]
 [4 5 6]]


In [4]:
y = np.roll(x, 1, axis=1)
print(y)

[[3 1 2]
 [6 4 5]]


In [5]:
y = np.roll(x, 1, axis=0)
print(y)

[[4 5 6]
 [1 2 3]]
