In [1]:
import numpy as np

In [2]:
x = np.array([[4,3],[2,1]])
x

array([[4, 3],
       [2, 1]])

In [5]:
x.sort(axis=1)
x

array([[3, 4],
       [1, 2]])

In [6]:
x.sort(axis=0)
x

array([[1, 2],
       [3, 4]])