In [1]:
import numpy as np

In [3]:
a = np.matrix([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])

print('Original Numpy array: \n', a)
print('Original Numpy array shape: \n', a.shape)

Original Numpy array: 
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
Original Numpy array shape: 
 (3, 4)


In [4]:
c = np.reshape(a, -1)
print('new shape: ', c)

new shape:  [[1 2 3 4 2 3 4 5 3 4 5 6]]


In [8]:
f = np.reshape(a, (2, -1))
print(f)

[[1 2 3 4 2 3]
 [4 5 3 4 5 6]]


In [10]:
g = np.reshape(a, (3, -1))
print(g)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]


In [13]:
j = np.reshape(a, (4, -1))
print(j)

[[1 2 3]
 [4 2 3]
 [4 5 3]
 [4 5 6]]
