In [1]:
import numpy as np

In [5]:
a = np.array([1,6,3,8])
print('Original: \n', a)

b = np.zeros((a.size, a.max() + 1))
b[np.arange(a.size), a] = 1

print('\n After: \n', b)

Original: 
 [1 6 3 8]

 After: 
 [[0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1.]]
