In [1]:
import numpy as np

In [3]:
x = np.array([
    [1,2,3],
    [3,4,6],
    [3,6,4],
    [9,7,4]
])

print('Numpy: \n', x)

Numpy: 
 [[1 2 3]
 [3 4 6]
 [3 6 4]
 [9 7 4]]


In [6]:
y = x[:,0]
print('x[:,0]: \n', y)

x[:,0]: 
 [1 3 3 9]


In [7]:
z = x[1,:]
print('x[1,:]: \n', z)

x[1,:]: 
 [3 4 6]


In [8]:
a = x[1:]
print('x[1:]: \n', a)

x[1:]: 
 [[3 4 6]
 [3 6 4]
 [9 7 4]]
